[opener]
json = [
    { run = 'jless "$@"', block = true, desc = "View JSON" },
    { run = 'nvim "$@"', block = true, desc = "Edit with nvim" },
]

[open]
prepend_rules = [
    { mime = "application/json", use = "json" },
]
